"""stock__price_history_table_addition

Revision ID: 0948e707cec4
Revises: 720dbb508456
Create Date: 2025-12-22 17:23:20.097173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0948e707cec4'
down_revision: Union[str, Sequence[str], None] = '720dbb508456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_price_history',
    sa.Column('stock_price_history_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('high_price', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('low_price', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('adjusted_close', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.stock_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('stock_price_history_id'),
    sa.UniqueConstraint('stock_id', 'price_date', name='uq_stock_date')
    )
    op.create_index(op.f('ix_stock_price_history_price_date'), 'stock_price_history', ['price_date'], unique=False)
    op.create_index(op.f('ix_stock_price_history_stock_id'), 'stock_price_history', ['stock_id'], unique=False)
    op.add_column('transactions', sa.Column('balance', sa.Integer(), nullable=False))
    op.add_column('transactions', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'transactions', ['parent_id'], ['transaction_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'parent_id')
    op.drop_column('transactions', 'balance')
    op.drop_index(op.f('ix_stock_price_history_stock_id'), table_name='stock_price_history')
    op.drop_index(op.f('ix_stock_price_history_price_date'), table_name='stock_price_history')
    op.drop_table('stock_price_history')
    # ### end Alembic commands ###
