"""enabled_column addition

Revision ID: 720dbb508456
Revises: 2e0668ced77e
Create Date: 2025-12-17 11:00:33.860557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '720dbb508456'
down_revision: Union[str, Sequence[str], None] = '2e0668ced77e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('enabled', sa.Boolean(), nullable=False))
    op.add_column('stocks', sa.Column('enabled', sa.Boolean(), nullable=False))
    op.add_column('transactions', sa.Column('enabled', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('enabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'enabled')
    op.drop_column('transactions', 'enabled')
    op.drop_column('stocks', 'enabled')
    op.drop_column('portfolios', 'enabled')
    # ### end Alembic commands ###
